# ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
# gitlab build pipeline for rpm packages
# ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

# variables
variables:
  GIT_SUBMODULE_STRATEGY: recursive
  CURL: curl -fSs --noproxy 'rie.gouv.fr, dgfip' --insecure
  ARCH: noarch
  REPO_URL: https://venezia.appli.dgfip/authscm/$VENEZIA_USER/ftp/sdeploy/$DIST/puppet-server-conf-servers/
   
# The ordering of elements in stages defines the ordering of jobs' execution
stages:
  - buildrpm

# executed before each job
before_script:
  - ${CURL} https://forge.dgfip.finances.rie.gouv.fr/dgfip/design/rpm/macros/-/raw/master/macros.rpmautospec >> ~/.rpmmacros
  - git config --global --add safe.directory ${PWD}
  - export VERSION="${CI_COMMIT_TAG}"
  - export RELEASE="$(rpmspec -q --qf '%{release}' ${CI_PROJECT_NAME}.spec)"
  - ln -s /home/rpmbuilder/rpmbuild/${ARCH}/RPMS

.buildrpm: &buildrpm
  tags:
    - rpmbuild
  script:
    - make srpm rpm
    - cp "/home/rpmbuilder/rpmbuild/RPMS/${ARCH}/${CI_PROJECT_NAME}-${VERSION}-${RELEASE}.${ARCH}.rpm" /var/tmp
    - cp "/home/rpmbuilder/rpmbuild/SRPMS/${CI_PROJECT_NAME}-${VERSION}-${RELEASE}.src.rpm" /var/tmp
    - ${CURL} -H "Authorization:\ Basic ${BASIC_AUTH}" -T /var/tmp/${CI_PROJECT_NAME}-${VERSION}-${RELEASE}.${ARCH}.rpm ${REPO_URL}
  only:
    - tags
  except:
    - branches

buildrpm/el8:
  <<: *buildrpm
  stage: buildrpm
  image: rbordet/rpmbuild-rocky8
  variables:
    DIST: el8

buildrpm/el7:
  <<: *buildrpm
  stage: buildrpm
  image: rbordet/rpmbuild-centos7
  variables:
    DIST: el7