# ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
# gitlab build pipeline for rpm packages
# ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

# variables
variables:
  GIT_SUBMODULE_STRATEGY: recursive
  CURL: "curl -fLSs --noproxy 'rie.gouv.fr' --insecure"
  ARCH: noarch
  REPO_URL: https://venezia.appli.dgfip/authscm/$VENEZIA_USER/ftp/sdeploy/$DIST/$CI_PROJECT_NAME
  CONFIG_REPO_URL: https://forge.dgfip.finances.rie.gouv.fr/dgfip/design/gitlab/gitlab-templates/-/raw/master/config-${DIST}.repo
   
# The ordering of elements in stages defines the ordering of jobs' execution
stages:
  - buildrpm

.buildrpm:
  tags:
    - rpmbuild
# executed before each job
  before_script:
    - sudo ${CURL} https://forge.dgfip.finances.rie.gouv.fr/dgfip/design/rpm/macros/-/raw/master/macros.rpmautospec -o /etc/rpm/macros.rpmautospec
    - git config --global --add safe.directory ${PWD}
    - export NAME=${CI_PROJECT_NAME}
    - export VERSION="${CI_COMMIT_TAG}"
    - export RELEASE="$(rpmspec -q --qf '%{release}' ${CI_PROJECT_NAME}.spec)"
    - sudo yum-config-manager --disable '*' >/dev/null
    - sudo yum-config-manager --add-repo=${CONFIG_REPO_URL}
    - sudo -E yum-builddep -y ${NAME}.spec
  script:
    - make srpm rpm
    - cp "/home/rpmbuilder/rpmbuild/RPMS/${ARCH}/${CI_PROJECT_NAME}-${CI_COMMIT_TAG}-${RELEASE}.${ARCH}.rpm" /var/tmp
    - cp "/home/rpmbuilder/rpmbuild/SRPMS/${CI_PROJECT_NAME}-${CI_COMMIT_TAG}-${RELEASE}.src.rpm" /var/tmp
    - '${CURL} -H "Authorization: Basic ${BASIC_AUTH}" -T /var/tmp/${CI_PROJECT_NAME}-${CI_COMMIT_TAG}-${RELEASE}.${ARCH}.rpm ${REPO_URL}/'
  rules:
    - if: $CI_COMMIT_TAG != null && $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH

buildrpm/el9:
  extends: .buildrpm
  stage: buildrpm
  image: rbordet/rpmbuild-rocky9
  variables:
    DIST: el9
    CONFIG_REPO_URL: http://repo.infra.dgfip/pub/distros/rockylinux-9-x86_64/rockylinux-9-x86_64.repo
  rules:
    - if: $RPMBUILD_EL9 != "no"

buildrpm/el8:
  extends: .buildrpm
  stage: buildrpm
  image: rbordet/rpmbuild-rocky8
  variables:
    DIST: el8
    CONFIG_REPO_URL: http://repo.infra.dgfip/pub/socles/socle-2022-8.04-x86_64/config.repo/socle-2022-8.04-x86_64-depot-20230517.repo
  rules:
    - if: $RPMBUILD_EL8 != "no"

buildrpm/el7:
  extends: .buildrpm
  stage: buildrpm
  image: rbordet/rpmbuild-centos7
  variables:
    DIST: el7
  rules:
    - if: $RPMBUILD_EL7 != "no"