# ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
# gitlab build pipeline for rpm packages
# ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

# variables
variables:
  ARCH: noarch
   
# The ordering of elements in stages defines the ordering of jobs' execution
stages:
  - buildrpm

# executed before each job
before_script:
  - curl -fSs --noproxy 'rie.gouv.fr' https://forge.dgfip.finances.rie.gouv.fr/dgfip/design/rpm/macros/-/raw/master/macros.rpmautospec >> ~/.rpmmacros
  - export VERSION="${CI_COMMIT_TAG}"
  - export RELEASE="$(rpmspec -q --qf '%{release}' ${CI_PROJECT_NAME}.spec)"
  - ln -s /home/rpmbuilder/rpmbuild/${ARCH}/RPMS

.buildrpm: &buildrpm
  tags:
    - rpmbuild
  script:
    - make srpm rpm
    - cp "/home/rpmbuilder/rpmbuild/RPMS/${ARCH}/${CI_PROJECT_NAME}-${VERSION}-${RELEASE}.${ARCH}.rpm" /var/tmp
    - cp "/home/rpmbuilder/rpmbuild/SRPMS/${CI_PROJECT_NAME}-${VERSION}-${RELEASE}.src.rpm" /var/tmp
  only:
    - tags
  except:
    - branches

buildrpm/el8:
  <<: *buildrpm
  stage: buildrpm
  image: rbordet/rpmbuild-rocky8
  variables:
    DIST: el8

buildrpm/el7:
  <<: *buildrpm
  stage: buildrpm
  image: jc21/rpmbuild-centos7
  variables:
    DIST: el7